### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by lyz-code** [bertvandepoel/tabby#13]
Hi, first thanks for the awesome development.

Do you plan to support Docker as an installation method?

It could be much easier for people to try your application.

**Comment by lyz-code** [comment]
Anyone interested in trying the application with docker can follow the next steps:

```bash
git clone https://github.com/bertvandepoel/tabby /tmp/tabby
cd /tmp/tabby

# Run the database
docker run -p 127.0.0.1:3306:3306  --name some-mariadb -e MARIADB_ROOT_PASSWORD=my-secret-pw -d mariadb
```

I had to connect to the database to create the `tabby` database

```bash
docker exec -it some-mariadb bash
mysql -u root -p localhost
```

```mysql
create database tabby;
```

Now we can run the application:

```bash
docker run --link some-mariadb -v /tmp/tabby/:/app -p 127.0.0.1:80:80 webdevops/php-nginx 
```

When you're in http://localhost/, and it asks you for the database connection, in the
host enter `some-mariadb`. You'll need to add an IBAN, you can use
http://randomiban.com/ to create a fake one.

**Comment by the-alpaka** [comment]
Hi @lyz-code I actually just made a docker image with tabby built into it today. You can pull it from docker using 'docker pull thealpaka/tabby'
Here's a link to my github with a more in-depth guide: [https://github.com/the-alpaka/docker_tabby](https://github.com/the-alpaka/docker_tabby)

**Comment by lyz-code** [comment]
Thanks @the-alpaka , I will take a look.
